parameters:
  - name: service_connection
  - name: resource_group_name
  - name: workspace_name
  - name: pipeline_artifact_name
  - name: pipeline_type
    values:
      - train
      - score

jobs:
  - job:
    displayName: Publish pipeline (${{ parameters.pipeline_type }})

    variables:
      - template: ../variables.yml
      - name: pipeline_action
        value: publish
      - name: pipeline_script
        value: src.${{ parameters.pipeline_type }}.${{ parameters.pipeline_type }}_pipeline
      - name: pipeline_metadata_file_path
        value: $(System.ArtifactsDirectory)/${{ parameters.pipeline_artifact_name }}/pipeline.json

    steps:
      - task: CmdLine@2
        displayName: Create anaconda environment
        inputs:
          script: |
            echo "##vso[task.prependpath]$CONDA/bin"
            conda env create --file $(dependencies_ci_cd)

      - task: DownloadBuildArtifacts@0
        displayName: Download pipeline metadata artifact
        inputs:
          artifactName: ${{ parameters.pipeline_artifact_name }}

      - task: AzureCLI@2
        displayName: Set subscription
        inputs:
          azureSubscription: $(service_connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Fail on error
            set -e

            # Get subscription id
            SUBSCRIPTION_ID=$(az account show --query id -o tsv)

            # Set variable for pipeline
            echo "##vso[task.setvariable variable=subscription_id]$SUBSCRIPTION_ID"

      - task: AzureCLI@2
        displayName: Set pipeline name
        inputs:
          azureSubscription: $(service_connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Fail on error
            set -e

            # Get subscription id
            PIPELINE_NAME=$(cat $(pipeline_metadata_file_path) | jq ".name" --raw-output)

            # Set variable for pipeline
            echo "##vso[task.setvariable variable=pipeline_name]$PIPELINE_NAME"

      - task: AzureCLI@2
        displayName: Publish pipeline
        inputs:
          azureSubscription: $(service_connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Activate conda environment
            source activate ci_env

            # Run script to publish pipeline
            python3 -m $(pipeline_script) \
            --subscription_id $(subscription_id) \
            --resource_group $(resource_group_name) \
            --workspace_name $(workspace_name) \
            --pipeline_name $(pipeline_name) \
            --pipeline_action $(pipeline_action) \
            --disable_published_pipelines \
